/**
 * Inventory Item data model
 * Maps to the REST API at https://prog2005.it.scu.edu.au/ArtGalley
 *
 * Key differences from A2:
 * - itemId: number (auto-incremented by server, not string like "ELEC001")
 * - featuredItem: 0 | 1 (replaces popularItem "Yes"/"No")
 * - specialNote: string (replaces comment)
 */
export interface InventoryItem {
  /** Unique identifier auto-generated by the server */
  itemId: number;

  /** Full name of the item */
  itemName: string;

  /** Category classification (e.g., "Laptop", "Phone", "Tablet") */
  itemCategory: string;

  /** Quantity in stock */
  itemQuantity: number;

  /** Unit price in AUD */
  itemPrice: number;

  /** Featured flag: 0 = normal, 1 = featured (replaces A2's popularItem) */
  featuredItem: number;

  /** Optional special note (replaces A2's comment) */
  specialNote?: string;
}

/**
 * DTO for creating a new inventory item
 * itemId is omitted as the server auto-generates it
 */
export interface CreateInventoryItem {
  itemName: string;
  itemCategory: string;
  itemQuantity: number;
  itemPrice: number;
  featuredItem: number;
  specialNote?: string;
}

/**
 * DTO for updating an existing inventory item
 * All fields are optional — only changed fields need to be sent
 */
export interface UpdateInventoryItem {
  itemName?: string;
  itemCategory?: string;
  itemQuantity?: number;
  itemPrice?: number;
  featuredItem?: number;
  specialNote?: string;
}

/**
 * Category options for the inventory system
 */
export const ITEM_CATEGORIES: string[] = [
  'Laptop',
  'Phone',
  'Tablet',
  'Monitor',
  'Keyboard',
  'Mouse',
  'Headset',
  'Camera',
  'Printer',
  'Other',
];

/**
 * Item name that cannot be deleted (A3 requirement)
 */
export const PROTECTED_ITEM_NAME = 'Laptop';
