/**
 * Inventory Item data model
 * Maps to the REST API at https://prog2005.it.scu.edu.au/ArtGalley
 *
 * API uses snake_case field names — these interfaces mirror the API exactly.
 * Key endpoints:
 *   GET    /ArtGalley            → all items
 *   GET    /ArtGalley/{name}     → items matching name (returns array)
 *   POST   /ArtGalley            → create item
 *   PUT    /ArtGalley/{name}     → update item by name
 *   DELETE /ArtGalley/{name}     → delete item by name
 */

/** Full item as returned by the API */
export interface InventoryItem {
  /** Unique identifier auto-generated by the server */
  item_id: number;

  /** Full name of the item */
  item_name: string;

  /** Category classification (e.g., "Electronics", "Tools") */
  category: string;

  /** Quantity in stock */
  quantity: number;

  /** Unit price in AUD */
  price: number;

  /** Supplier name */
  supplier_name: string;

  /** Stock status (e.g., "In stock", "Low stock", "Out of stock") */
  stock_status: string;

  /** Featured flag: 0 = normal, 1 = featured */
  featured_item: number;

  /** Optional special note */
  special_note?: string;
}

/**
 * DTO for creating a new inventory item
 * item_id is omitted as the server auto-generates it
 */
export interface CreateInventoryItem {
  item_name: string;
  category: string;
  quantity: number;
  price: number;
  supplier_name: string;
  stock_status: string;
  featured_item: number;
  special_note?: string;
}

/**
 * DTO for updating an existing inventory item
 * All fields are optional — only changed fields need to be sent
 */
export interface UpdateInventoryItem {
  item_name?: string;
  category?: string;
  quantity?: number;
  price?: number;
  supplier_name?: string;
  stock_status?: string;
  featured_item?: number;
  special_note?: string;
}

/**
 * Category options for the inventory system
 */
export const ITEM_CATEGORIES: string[] = [
  'Electronics',
  'Furniture',
  'Tools',
  'Office Supplies',
  'Software',
  'Other',
];

/**
 * Stock status options
 */
export const STOCK_STATUSES: string[] = [
  'In stock',
  'Low stock',
  'Out of stock',
];

/**
 * Item name that cannot be deleted (A3 requirement)
 */
export const PROTECTED_ITEM_NAME = 'Laptop';
